default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: takegaharakose
  password:
  pool: 5

development:
  <<: *default
  database: wonderful_post_app_development

test:
  <<: *default
  database: wonderful_post_app_test
