name: CI

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop -c .rubocop.yml -f github

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true
      - name: Brakeman
        run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node (for Vite)
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'yarn'

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install JS deps (Yarn)
        run: yarn install --immutable

      - name: Build assets (Vite)
        run: yarn build
