name: CI

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop -c .rubocop.yml -f github

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true
      - name: Brakeman
        run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js (for Vite)
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'yarn' # ← キャッシュを Yarn 用に設定

      - name: Enable Corepack and set Yarn 4.9.2
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn -v

      - name: Install JS deps (Yarn)
        run: yarn install --immutable

      - name: Build assets (Vite)
        run: yarn build
