name: CI

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop -c .rubocop.yml -f github

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack and prepare Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Use Yarn 4
        run: yarn -v  # この時点で yarn 4.9.2 が使われるはずです

      - name: Install JS dependencies
        run: yarn install --immutable

      - name: Build assets with Vite
        run: yarn build
